#!/bin/bash

# We don't stop the script on errors cause we want to backup all data we could backuped
#set -eu

borg_id=$1
errors=""
current_date=$(date +"%y%m%d_%H%M")
log_file="/var/log/${borg_id}/${current_date}.log"
err_file="/var/log/${borg_id}/${current_date}.err"
mkdir -p "/var/log/${borg_id}"
if [[ -z "$borg_id" ]]
then
    echo "This script expects a borg app id as first argument" >&2
    exit 1
fi

filter_hooks() {
    ls /usr/share/yunohost/hooks/backup/ /etc/yunohost/hooks.d/backup/ | grep "\-$1_" | cut -d"-" -f2 | uniq
}

fail_if_partially_failed() {
    grep Skipped|Error
}

# Backup system part conf
conf=$(yunohost app setting ${borg_id} conf)
if [ $conf -eq 1 ]
then
    if ! yunohost backup create -n auto_conf --method ${borg_id}_app --system $(filter_hooks conf) 2> $err_file > $log_file ; then
        errors="$errors\nconf: Error"
    fi
fi

# Backup system data
data=$(yunohost app setting $app data)
if [ $data -eq 1 ]
then
    if ! yunohost backup create -n auto_data --method ${borg_id}_app --system $(filter_hooks data) 2> $err_file > $log_file ; then
        errors="$errors\ndata: Error"
    fi
fi

# Backup all apps independently
apps=$(yunohost app setting ${borg_id} apps)
for application in $(ls /etc/yunohost/apps/*/scripts/backup | cut -d / -f 5); do
    backup_app=false
    if [[ "$apps" = "all" ]]; then
          backup_app=true
    else
        for selected_app in $(echo $apps | tr "," " ");do
            if [[ "$selected_app" == "$application" ]]; then
              backup_app=true
              break
            fi
        done
    fi
    if [ "$backup_app" == "true" ];then
        if ! yunohost backup create -n auto_$application --method ${borg_id}_app --apps $application 2> $err_file > $log_file ; then
            errors="$errors\$application: Error"
        fi
    fi
done
partial_errors="$(cat $log_file | grep -E "Error|Skipped")"
if [ ! -z "$partial_errors" ]; then
    errors="$errors\n$partial_errors"
fi

# Send mail on backup (partially) failed
domain=$(hostname)
if [ ! -z "$errors" ]; then
    cat $errors | mail -s "[borg] Backup failed from $domain onto $repo" root
else
    cat $log_file | mail -s "[borg] Backup succeed from $domain onto $repo" root
fi
