#!/bin/bash

source /usr/share/yunohost/helpers

ynh_print_info "Declaring files to be backed up..."

#=================================================
# SYSTEM CONFIGURATION
#=================================================

ynh_backup "/etc/systemd/system/$app.service"
ynh_backup "/etc/systemd/system/$app.timer"

ynh_backup "/etc/yunohost/hooks.d/backup_method/05-${app}_app"
ynh_backup "/etc/sudoers.d/$app"

ynh_backup "/root/.ssh/id_${app}_ed25519" || true
ynh_backup "/root/.ssh/id_${app}_ed25519.pub" || true

ynh_backup "$install_dir/backup-with-borg"
ynh_backup "$install_dir/logging.conf"
ynh_backup "$install_dir/wrapper"
ynh_backup "$install_dir/.env"

ynh_backup "/etc/logrotate.d/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
