#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SERVICE INTEGRATION IN YUNOHOST
#=================================================

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status $app >/dev/null; then
    ynh_script_progression "Removing $app service integration..."
    yunohost service remove $app
fi

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

systemctl stop $app.timer
systemctl disable $app.timer --quiet
ynh_config_remove_systemd

ynh_safe_rm "/etc/systemd/system/$app.timer"
ynh_safe_rm "/etc/yunohost/hooks.d/backup_method/05-${app}_app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
